services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: local_graphql
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app 
    command: ["python3", "simple_main.py"]