services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    # build: .
    image: mygraphql:0.0.9
    container_name: local_graphql
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app
      - ./docs:/app/docs
    command: ["python3", "simple_main.py"]

volumes:
  mongo_data:
    driver: local