"""Initial migration

Revision ID: 9f36f2a52c47
Revises: 
Create Date: 2024-12-05 08:11:51.228137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f36f2a52c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signup_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('expired_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expired_time')
    op.drop_column('user', 'signup_time')
    # ### end Alembic commands ###
